// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amzfjpfikgzizvbrkbet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtemZqcGZpa2d6aXp2YnJrYmV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTI0ODksImV4cCI6MjA3MTg4ODQ4OX0.ErdjETv8OZDToXFXg9_vRoUwgRvacYcqTT5k1QkQbtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});